spring:
  datasource:
    url: jdbc:mysql://localhost:3306/prova
    username: root
    password: Milanista1997
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create-drop
  jackson:
    serialization:
      fail-on-empty-beans: false
server:
  port: 5050
